//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HocSinh_EF01.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QL_HocSinh_EF01.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma hoc sinh phai la so nguyen !.
        /// </summary>
        internal static string ErrHocSinhID {
            get {
                return ResourceManager.GetString("ErrHocSinhID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ten khong duoc qua 20 ky tu va co it nhat 2 tu !.
        /// </summary>
        internal static string ErrHoTen {
            get {
                return ResourceManager.GetString("ErrHoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma lop phai la so nguyen !.
        /// </summary>
        internal static string ErrLopID {
            get {
                return ResourceManager.GetString("ErrLopID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay sinh phai thuoc 2001-2013.
        /// </summary>
        internal static string ErrNgaySinh {
            get {
                return ResourceManager.GetString("ErrNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ErrQueQuan {
            get {
                return ResourceManager.GetString("ErrQueQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten loop khong duoc qua 10 ky tu !.
        /// </summary>
        internal static string ErrTenLop {
            get {
                return ResourceManager.GetString("ErrTenLop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma hoc sinh: .
        /// </summary>
        internal static string InpHocSinhID {
            get {
                return ResourceManager.GetString("InpHocSinhID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten hoc sinh: .
        /// </summary>
        internal static string InpHoTen {
            get {
                return ResourceManager.GetString("InpHoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma lop: .
        /// </summary>
        internal static string InpLopID {
            get {
                return ResourceManager.GetString("InpLopID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ngay sinh: .
        /// </summary>
        internal static string InpNgaySinh {
            get {
                return ResourceManager.GetString("InpNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap que quan: .
        /// </summary>
        internal static string InpQueQuan {
            get {
                return ResourceManager.GetString("InpQueQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten lop: .
        /// </summary>
        internal static string InpTenLop {
            get {
                return ResourceManager.GetString("InpTenLop", resourceCulture);
            }
        }
    }
}
